User.create(name: "Kameron", email: "kam.hungerford@gmail.com")
User.create(name: "Grace", email: "gracexpwnz@gmail.com")
User.create(name: "Linda", email: "lmhungerford@yahoo.com")
User.create(name: "Blake", email: "blakepetes@gmail.com")

Song.create(title: "Basshead", artist: "Bassnectar", album: "Timestrech", album_cover: "https://ibb.co/YhFJz6J", user_id: 1)
Song.create(title: "Trigger Happy", artist: "Liquid Stranger", album: "Tales of Wakaan", album_cover: "https://ibb.co/SxXRp48", user_id: 1)
Song.create(title: "Harmony", artist: "Clozee", album: "Harmony", album_cover: "https://ibb.co/Pts5w12", user_id: 1)
Song.create(title: "Griztronics", artist: "GRIZ & Subtronics", album: "Bangers[2].Zip", album_cover: "https://ibb.co/QnVLVtm", user_id: 1)
Song.create(title: "Conrank", artist: "Drum In Time", album: "What's a FKNG Conrank", album_cover: "https://ibb.co/h8Kqnq0", user_id: 1)